theme = "tokyonight"

[keys.normal]
C-s = ":w"
C-e = "goto_line_end"
C-a = "goto_line_start"
"Cmd-A-left" = "move_prev_word_start"
"Cmd-A-right" = "move_next_word_end"
C-k = "kill_to_line_end"
"C-/" = "toggle_comments"
S-left = "extend_char_left"
S-right = "extend_char_right"
S-up = "extend_line_up"
S-down = "extend_line_down"
S-home = "extend_to_line_start"
S-end = "extend_to_line_end"
"Cmd-a" = "select_all"

A-w = "@<space>w" # open window commands (splits, etc)
A-z = ":toggle-option soft-wrap.enable"

[keys.insert]
C-e = "goto_line_end"
C-a = "goto_line_start"
"Cmd-A-left" = "move_prev_word_start"
"Cmd-A-right" = "move_next_word_end"
C-k = "kill_to_line_end"
"C-/" = "toggle_comments"
S-left = "extend_char_left"
S-right = "extend_char_right"
S-up = "extend_line_up"
S-down = "extend_line_down"
S-home = "extend_to_line_start"
S-end = "extend_to_line_end"
C-y = [":clipboard-yank"]
"Cmd-a" = "select_all"

A-w = "@<esc><space>w"
A-z = ":toggle-option soft-wrap.enable"

[editor]
clipboard-provider = "termcode"
insert-final-newline = true
trim-final-newlines = true
trim-trailing-whitespace = true

[editor.file-picker]
hidden = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true

[editor.soft-wrap]
enable = true
max-wrap = 25
wrap-indicator = ""
